package demo_qly.MANAGER;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class FRNguoi_cach_ly extends javax.swing.JFrame {
    DefaultTableModel tblModel = new DefaultTableModel();
    SimpleDateFormat date_format = new SimpleDateFormat("yyyy");
    Nguoi_cach_ly_DAO dao = new Nguoi_cach_ly_DAO();
    public FRNguoi_cach_ly() {
        initComponents();
        ngclList();
        setLocationRelativeTo(null);
    }
    public void ngclList() {
       try{
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_lq_covid" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người liên quan Covid","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Trạng thái","Nơi điều trị","Liên quan đến", "Lịch sử quá trình" };
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_lien_quan");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getString("dia_chi");
                   row[6] = rs.getString("trang_thai");
                   row[7] = rs.getString("noi_dieu_tri");
                   row[8] = rs.getString("lien_quan_den_ai");
                   row[9] = rs.getString("lich_su_qua_trinh");
                   this.tblModel.addRow(row);
                }                      
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }
}

//public void show_ncl(){
//  ArrayList<Nguoi_cach_ly> list = ngclList();
//  DefaultTableModel tblModel = (DefaultTableModel)tbNCL.getModel();  
//   Object[] row = new Object[10];
//   for(int i=0;i<list.size(); i++){
//     row[0] = list.get(i).getMa_nguoi_LQ();
//     row[1] = list.get(i).getHo_LQ();
//     row[2] = list.get(i).getTen_LQ();
//     row[3] = list.get(i).getCMND_CCCD();
//     row[4] = list.get(i).getnamSinh();
//     row[5] = list.get(i).getdiaChi();
//     row[6] = list.get(i).gettrangThai();
//     row[7] = list.get(i).getnoiDieuTri();
//     row[8] = list.get(i).getlienQuanDenAi();
//     row[9] = list.get(i).getlichsuTrangThai();
//     }
//      tblModel.addRow(row);
//}


  public void fillData(){
     DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();
     
     //tbModel.setRowCount(0);
     for (Nguoi_cach_ly Ngg : dao.getAllNCL()){
         Object [] rowData = new Object[10];
         rowData[0] = Ngg.getMa_nguoi_LQ();
         rowData[1] = Ngg.getHo_LQ();
         rowData[2] = Ngg.getTen_LQ();
         rowData[3] = Ngg.getCMND_CCCD();
         rowData[4] = Ngg.getnamSinh();
         rowData[5] = Ngg.getdiaChi();
         rowData[6] = Ngg.gettrangThai();
         rowData[7] = Ngg.getnoiDieuTri();
         rowData[8] = Ngg.getlienQuanDenAi();
         rowData[9] = Ngg.getlichsuTrangThai();
         tbModel.addRow(rowData);
}

}
//    private final JLabel lblStatus = new JLabel();
//    private JLabel lblCount;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

jTextField3 = new javax.swing.JTextField();
jTextField5 = new javax.swing.JTextField();
jTextField7 = new javax.swing.JTextField();
jTextField8 = new javax.swing.JTextField();
jTextField9 = new javax.swing.JTextField();
jTextField10 = new javax.swing.JTextField();
jTextField11 = new javax.swing.JTextField();
jTextField12 = new javax.swing.JTextField();
jTextField14 = new javax.swing.JTextField();
jTextField17 = new javax.swing.JTextField();
jTextField18 = new javax.swing.JTextField();
jTextField19 = new javax.swing.JTextField();
jTextField20 = new javax.swing.JTextField();
jTextField22 = new javax.swing.JTextField();
jTextField23 = new javax.swing.JTextField();
jLabel1 = new javax.swing.JLabel();
jLabel2 = new javax.swing.JLabel();
jLabel3 = new javax.swing.JLabel();
jLabel4 = new javax.swing.JLabel();
jLabel5 = new javax.swing.JLabel();
jLabel6 = new javax.swing.JLabel();
jLabel7 = new javax.swing.JLabel();
jLabel8 = new javax.swing.JLabel();
jLabel9 = new javax.swing.JLabel();
jLabel10 = new javax.swing.JLabel();
jLabel11 = new javax.swing.JLabel();
txt_maLQ = new javax.swing.JTextField();
txt_cmnd_cccd = new javax.swing.JTextField();
txt_hoLQ = new javax.swing.JTextField();
txt_tenLQ = new javax.swing.JTextField();
jLabel12 = new javax.swing.JLabel();
txt_namSinh = new javax.swing.JTextField();
txt_diaChi = new javax.swing.JTextField();
txt_lq_den_ai = new javax.swing.JTextField();
txt_lichSuQT = new javax.swing.JTextField();
txt_trangThai = new javax.swing.JComboBox<>();
txt_noiDieuTri = new javax.swing.JComboBox<>();
btn_find = new javax.swing.JButton();
btn_add = new javax.swing.JButton();
btn_edit = new javax.swing.JButton();
btn_delete = new javax.swing.JButton();
btn_exist = new javax.swing.JButton();
jScrollPane1 = new javax.swing.JScrollPane();
tbNCL = new javax.swing.JTable();
jButton1 = new javax.swing.JButton();
jButton2 = new javax.swing.JButton();
jButton3 = new javax.swing.JButton();
jButton4 = new javax.swing.JButton();
jButton5 = new javax.swing.JButton();

jTextField3.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField3ActionPerformed(evt);
}
});

jTextField5.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField5ActionPerformed(evt);
}
});

jTextField7.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField7ActionPerformed(evt);
}
});

jTextField8.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField8ActionPerformed(evt);
}
});

jTextField9.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField9ActionPerformed(evt);
}
});

jTextField10.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField10ActionPerformed(evt);
}
});

jTextField11.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField11ActionPerformed(evt);
}
});

jTextField12.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField12ActionPerformed(evt);
}
});

jTextField14.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField14ActionPerformed(evt);
}
});

jTextField17.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField17ActionPerformed(evt);
}
});

jTextField18.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField18ActionPerformed(evt);
}
});

jTextField19.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField19ActionPerformed(evt);
}
});

jTextField20.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField20ActionPerformed(evt);
}
});

jTextField22.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField22ActionPerformed(evt);
}
});

jTextField23.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField23ActionPerformed(evt);
}
});

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
jLabel1.setText("QUAN LY NGUOI LIEN QUAN COVID-19");

jLabel2.setText("MA NGUOI LIEN QUAN: ");

jLabel3.setText("HO NGUOI LIEN QUAN: ");

jLabel4.setText("TEN NGUOI LIEN QUAN: ");

jLabel5.setText("CMND/CCCD:");

jLabel6.setText("NAM SINH: ");

jLabel7.setText("DIA CHI: ");

jLabel8.setText("TRANG THAI: ");

jLabel9.setText("NOI DIEU TRI:");

jLabel10.setText("LIEN QUAN DEN: ");

jLabel11.setText("LICH SU QUA TRINH: ");

txt_maLQ.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_maLQActionPerformed(evt);
}
});

txt_cmnd_cccd.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_cmnd_cccdActionPerformed(evt);
}
});

txt_hoLQ.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_hoLQActionPerformed(evt);
}
});

txt_tenLQ.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_tenLQActionPerformed(evt);
}
});

txt_namSinh.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_namSinhActionPerformed(evt);
}
});

txt_diaChi.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_diaChiActionPerformed(evt);
}
});

txt_lq_den_ai.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_lq_den_aiActionPerformed(evt);
}
});

txt_lichSuQT.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_lichSuQTActionPerformed(evt);
}
});

txt_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F0", "F1", "F2", "F3" }));

txt_noiDieuTri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MDT1", "MDT2", "MDT3", "MDT4", "MDT5", "MDT6", "MDT7" }));
txt_noiDieuTri.addItemListener(new java.awt.event.ItemListener() {
public void itemStateChanged(java.awt.event.ItemEvent evt) {
txt_noiDieuTriItemStateChanged(evt);
}
});
txt_noiDieuTri.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_noiDieuTriActionPerformed(evt);
}
});

btn_find.setText("TÌM KIẾM");
btn_find.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btn_findActionPerformed(evt);
}
});

btn_add.setText("THÊM MỚI");
btn_add.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btn_addActionPerformed(evt);
}
});

btn_edit.setText("SỬA");
btn_edit.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btn_editActionPerformed(evt);
}
});

btn_delete.setText("XÓA");
btn_delete.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btn_deleteActionPerformed(evt);
}
});

btn_exist.setText("THOÁT");
btn_exist.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btn_existActionPerformed(evt);
}
});

tbNCL.setModel(new javax.swing.table.DefaultTableModel(
new Object [][] {

},
new String [] {
"Mã người liên quan Covid", "Họ", "Tên", "CMND/CCCD", "Năm sinh", "Địa chỉ", "Trạng thái", "Nơi điều trị", "Liên quan đến", "Lịch sử quá trình"
}
));
tbNCL.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
tbNCLMouseClicked(evt);
}
});
jScrollPane1.setViewportView(tbNCL);

jButton1.setText("Quay lại");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});

jButton2.setText("Sắp xếp theo tuổi giảm dần");
jButton2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton2ActionPerformed(evt);
}
});

jButton3.setText("Sắp xếp theo tuổi tăng dần");
jButton3.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton3ActionPerformed(evt);
}
});

jButton4.setText("Sắp xếp theo trạng thái");
jButton4.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton4ActionPerformed(evt);
}
});

jButton5.setText("Thống kê 1");
jButton5.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton5ActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(19, 19, 19)
.addComponent(jButton1)
.addGap(95, 95, 95)
.addComponent(jLabel1)
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel2)
.addGap(30, 30, 30)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(txt_maLQ, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(txt_hoLQ, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addComponent(jLabel3)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel4)
.addComponent(jLabel5))
.addGap(25, 25, 25)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(txt_cmnd_cccd, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
.addComponent(txt_namSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
.addComponent(txt_diaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
.addComponent(txt_tenLQ)))
.addComponent(jLabel6)
.addComponent(jLabel7)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel8)
.addComponent(jLabel9))
.addGap(83, 83, 83)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(txt_noiDieuTri, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(txt_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel10)
.addComponent(jLabel11))
.addGap(40, 40, 40)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(txt_lq_den_ai, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(txt_lichSuQT, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(btn_find, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(btn_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(267, 267, 267))
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel12)
.addGap(0, 0, Short.MAX_VALUE))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addGap(0, 0, Short.MAX_VALUE)
.addComponent(btn_exist, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addGap(0, 22, Short.MAX_VALUE)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(77, Short.MAX_VALUE))))
.addGroup(layout.createSequentialGroup()
.addGap(129, 129, 129)
.addComponent(jButton2)
.addGap(18, 18, 18)
.addComponent(jButton3)
.addGap(39, 39, 39)
.addComponent(jButton4)
.addGap(0, 0, Short.MAX_VALUE))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jButton5)
.addGap(119, 119, 119))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton1))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(18, 18, 18)
.addComponent(btn_find, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE))
.addGroup(layout.createSequentialGroup()
.addGap(35, 35, 35)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(txt_maLQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel2))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3)
.addComponent(txt_hoLQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel4)
.addComponent(txt_tenLQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel5)
.addComponent(txt_cmnd_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(txt_namSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel7)
.addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel8)
.addComponent(txt_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel9)
.addComponent(txt_noiDieuTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel10)
.addComponent(txt_lq_den_ai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel11)
.addComponent(txt_lichSuQT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(52, 52, 52)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jButton2)
.addComponent(jButton3)
.addComponent(jButton4))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
.addGroup(layout.createSequentialGroup()
.addGap(65, 65, 65)
.addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(56, 56, 56)
.addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(39, 39, 39)
.addComponent(jButton5)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(84, 84, 84)
.addComponent(jLabel12)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(btn_exist, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
);

pack();
}// </editor-fold>//GEN-END:initComponents

    private void txt_maLQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maLQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maLQActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void txt_lq_den_aiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lq_den_aiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lq_den_aiActionPerformed

    private void txt_tenLQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenLQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenLQActionPerformed

    private void txt_diaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diaChiActionPerformed

    private void txt_hoLQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hoLQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hoLQActionPerformed

    private void txt_namSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namSinhActionPerformed

    private void txt_cmnd_cccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cmnd_cccdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cmnd_cccdActionPerformed

    private void txt_lichSuQTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lichSuQTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lichSuQTActionPerformed

    public void resetForm(){
    txt_maLQ.setText("");
    txt_hoLQ.setText("");
    txt_tenLQ.setText("");
    txt_cmnd_cccd.setText("");
    txt_namSinh.setText("");
    txt_diaChi.setText("");
    txt_trangThai.setSelectedIndex(0);
    txt_noiDieuTri.setSelectedIndex(0);
    txt_lq_den_ai.setText("");
    txt_lichSuQT.setText("");
    
}
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
     String s1 = txt_maLQ.getText();
     String s2 = txt_hoLQ.getText();
     String s3 = txt_tenLQ.getText();
     String s4 = txt_cmnd_cccd.getText();
     String s5 = txt_namSinh.getText();
     String s6 = txt_diaChi.getText();
     String s7 = txt_trangThai.getSelectedItem().toString();
     String s8 = txt_noiDieuTri.getSelectedItem().toString();
     String s9 = txt_lq_den_ai.getText();
     String s10 = txt_lichSuQT.getText();    
     if (s1.equals("") || s2.equals("") || s3.equals("") || s4.equals("") || s5.equals("") || s6.equals("") || s7.equals("") || s8.equals("") || s9.equals("") || s10.equals(""))
       {
        JOptionPane.showMessageDialog(this,"Please fill in all the information!!!");
}       else{    
     try{
     Class.forName("oracle.jdbc.driver.OracleDriver");       
     Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
     String orc ="insert into Nguoi_lq_covid"
                 +"(ma_nguoi_lien_quan, ho, ten, CMND, nam_sinh, dia_chi, trang_thai, noi_dieu_tri, lien_quan_den_ai, lich_su_qua_trinh)"
                 +"values(?,?,?,?,?,?,?,?,?,?)";
      PreparedStatement pst = con.prepareStatement(orc);
      pst.setString(1, txt_maLQ.getText());
      pst.setString(2, txt_hoLQ.getText());
      pst.setString(3, txt_tenLQ.getText());
      pst.setString(4, txt_cmnd_cccd.getText());
      pst.setString(5, txt_namSinh.getText());
      pst.setString(6, txt_diaChi.getText());
      pst.setString(7, txt_trangThai.getSelectedItem().toString());
      pst.setString(8, txt_noiDieuTri.getSelectedItem().toString());
      pst.setString(9, txt_lq_den_ai.getText());
      pst.setString(10, txt_lichSuQT.getText());

      pst.executeUpdate();
      JOptionPane.showMessageDialog(this,"Insert Successfully");

   } catch(Exception e)
{
       JOptionPane.showMessageDialog(this,e.getMessage());
}
}try{
      DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();     
     tbModel.setRowCount(0);  
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_lq_covid" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người liên quan Covid","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Trạng thái","Nơi điều trị","Liên quan đến", "Lịch sử quá trình" };
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_lien_quan");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getString("dia_chi");
                   row[6] = rs.getString("trang_thai");
                   row[7] = rs.getString("noi_dieu_tri");
                   row[8] = rs.getString("lien_quan_den_ai");
                   row[9] = rs.getString("lich_su_qua_trinh");
                   this.tblModel.addRow(row);
             } 
                     
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }   
    }//GEN-LAST:event_btn_addActionPerformed





    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
     String s1 = txt_maLQ.getText();
     String s2 = txt_hoLQ.getText();
     String s3 = txt_tenLQ.getText();
     String s4 = txt_cmnd_cccd.getText();
     String s5 = txt_namSinh.getText();
     String s6 = txt_diaChi.getText();
     String s7 = txt_trangThai.getSelectedItem().toString();
     String s8 = txt_noiDieuTri.getSelectedItem().toString();
     String s9 = txt_lq_den_ai.getText();
     String s10 = txt_lichSuQT.getText();    
     if (s1.equals("") || s2.equals("") || s3.equals("") || s4.equals("") || s5.equals("") || s6.equals("") || s7.equals("") || s8.equals("") || s9.equals("") || s10.equals(""))
       {
        JOptionPane.showMessageDialog(this,"Please fill in all the information!!!");
}       else{ 
     try{
     Class.forName("oracle.jdbc.driver.OracleDriver");       
     Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
     String orc ="UPDATE Nguoi_lq_covid set ho=?, ten=?, CMND=?, nam_sinh=?, dia_chi=?, trang_thai=?, noi_dieu_tri=?, lien_quan_den_ai=?, lich_su_qua_trinh=? where ma_nguoi_lien_quan=?";
       PreparedStatement pst = con.prepareStatement(orc);

      pst.setString(1, txt_hoLQ.getText());
      pst.setString(2, txt_tenLQ.getText());
      pst.setString(3, txt_cmnd_cccd.getText());
      pst.setString(4, txt_namSinh.getText());
      pst.setString(5, txt_diaChi.getText());
      pst.setString(6, txt_trangThai.getSelectedItem().toString());
      pst.setString(7, txt_noiDieuTri.getSelectedItem().toString());
      pst.setString(8, txt_lq_den_ai.getText());
      pst.setString(9, txt_lichSuQT.getText());
      pst.setString(10, txt_maLQ.getText());

      pst.executeUpdate();
      JOptionPane.showMessageDialog(this,"Update Successfully");

   } catch(Exception e)
{
       JOptionPane.showMessageDialog(this,e.getMessage());
}
}   
try{
      DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();     
     tbModel.setRowCount(0);  
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_lq_covid" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người liên quan Covid","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Trạng thái","Nơi điều trị","Liên quan đến", "Lịch sử quá trình" };
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_lien_quan");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getString("dia_chi");
                   row[6] = rs.getString("trang_thai");
                   row[7] = rs.getString("noi_dieu_tri");
                   row[8] = rs.getString("lien_quan_den_ai");
                   row[9] = rs.getString("lich_su_qua_trinh");
                   this.tblModel.addRow(row);
             } 
                     
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }   
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_existActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_existActionPerformed
        dispose();
    }//GEN-LAST:event_btn_existActionPerformed


private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed

try{
            DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();     
            tbModel.setRowCount(0);  
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();

            String orc = "select * from Nguoi_lq_covid where ma_nguoi_lien_quan= " + txt_maLQ.getText() ;
            //PreparedStatement pst = con.prepareStatement(orc);
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người liên quan Covid", "Họ", "Tên", "CMND/CCCD", "Năm sinh", "Địa chỉ", "Trạng thái","Nơi điều trị","Liên quan đến", "Lịch sử quá trình" };
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_lien_quan");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getString("dia_chi");
                   row[6] = rs.getString("trang_thai");
                   row[7] = rs.getString("noi_dieu_tri");
                   row[8] = rs.getString("lien_quan_den_ai");
                   row[9] = rs.getString("lich_su_qua_trinh");
                   this.tblModel.addRow(row);
             }          
              JOptionPane.showMessageDialog(this,"Find Successfully");            
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }
}//GEN-LAST:event_btn_findActionPerformed

private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

 try{
     Class.forName("oracle.jdbc.driver.OracleDriver");       
     Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
     String orc ="delete from Nguoi_lq_covid where ma_nguoi_lien_quan=?";
      PreparedStatement pst = con.prepareStatement(orc);
      pst.setString(1, txt_maLQ.getText());
      pst.executeUpdate();
      JOptionPane.showMessageDialog(this,"Delete Successfully");
   } catch(Exception e)
{
       JOptionPane.showMessageDialog(this,e.getMessage());
} 
try{
      DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();     
     tbModel.setRowCount(0);  
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_lq_covid" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người liên quan Covid","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Trạng thái","Nơi điều trị","Liên quan đến", "Lịch sử quá trình" };
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_lien_quan");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getString("dia_chi");
                   row[6] = rs.getString("trang_thai");
                   row[7] = rs.getString("noi_dieu_tri");
                   row[8] = rs.getString("lien_quan_den_ai");
                   row[9] = rs.getString("lich_su_qua_trinh");
                   this.tblModel.addRow(row);
             } 
                     
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }
  
}//GEN-LAST:event_btn_deleteActionPerformed

private void tbNCLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNCLMouseClicked

}//GEN-LAST:event_tbNCLMouseClicked

private void txt_noiDieuTriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txt_noiDieuTriItemStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_txt_noiDieuTriItemStateChanged

private void txt_noiDieuTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noiDieuTriActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_noiDieuTriActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Manage_manager mager = new Manage_manager();
        mager.show();}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
      DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();     
     tbModel.setRowCount(0);  
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_lq_covid ORDER BY nam_sinh DESC" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người liên quan Covid","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Trạng thái","Nơi điều trị","Liên quan đến", "Lịch sử quá trình" };
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_lien_quan");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getString("dia_chi");
                   row[6] = rs.getString("trang_thai");
                   row[7] = rs.getString("noi_dieu_tri");
                   row[8] = rs.getString("lien_quan_den_ai");
                   row[9] = rs.getString("lich_su_qua_trinh");
                   this.tblModel.addRow(row);
             } 
                     
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
      DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();     
     tbModel.setRowCount(0);  
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_lq_covid ORDER BY nam_sinh ASC" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người liên quan Covid","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Trạng thái","Nơi điều trị","Liên quan đến", "Lịch sử quá trình" };
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_lien_quan");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getString("dia_chi");
                   row[6] = rs.getString("trang_thai");
                   row[7] = rs.getString("noi_dieu_tri");
                   row[8] = rs.getString("lien_quan_den_ai");
                   row[9] = rs.getString("lich_su_qua_trinh");
                   this.tblModel.addRow(row);
             } 
                     
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
      DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();     
     tbModel.setRowCount(0);  
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_lq_covid ORDER BY trang_thai ASC" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người liên quan Covid","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Trạng thái","Nơi điều trị","Liên quan đến", "Lịch sử quá trình" };
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_lien_quan");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getString("dia_chi");
                   row[6] = rs.getString("trang_thai");
                   row[7] = rs.getString("noi_dieu_tri");
                   row[8] = rs.getString("lien_quan_den_ai");
                   row[9] = rs.getString("lich_su_qua_trinh");
                   this.tblModel.addRow(row);
             } 
                     
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }

}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed



}//GEN-LAST:event_jButton5ActionPerformed
/**/
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConnectDB().createCon();
                    }
                     catch(Exception E){
                     E.printStackTrace();
                    }
                     new FRNguoi_cach_ly().setVisible(true);
                    }
           }
           );
    
    }
    public static class ConnectDB {
     ConnectDB(){};
    public static  Connection createCon() throws ClassNotFoundException, SQLException{
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");
            return connection;
        }
        catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
            return null;            
        }
    }
}   


// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton btn_add;
private javax.swing.JButton btn_delete;
private javax.swing.JButton btn_edit;
private javax.swing.JButton btn_exist;
private javax.swing.JButton btn_find;
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JButton jButton3;
private javax.swing.JButton jButton4;
private javax.swing.JButton jButton5;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel10;
private javax.swing.JLabel jLabel11;
private javax.swing.JLabel jLabel12;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JLabel jLabel7;
private javax.swing.JLabel jLabel8;
private javax.swing.JLabel jLabel9;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JTextField jTextField10;
private javax.swing.JTextField jTextField11;
private javax.swing.JTextField jTextField12;
private javax.swing.JTextField jTextField14;
private javax.swing.JTextField jTextField17;
private javax.swing.JTextField jTextField18;
private javax.swing.JTextField jTextField19;
private javax.swing.JTextField jTextField20;
private javax.swing.JTextField jTextField22;
private javax.swing.JTextField jTextField23;
private javax.swing.JTextField jTextField3;
private javax.swing.JTextField jTextField5;
private javax.swing.JTextField jTextField7;
private javax.swing.JTextField jTextField8;
private javax.swing.JTextField jTextField9;
private javax.swing.JTable tbNCL;
private javax.swing.JTextField txt_cmnd_cccd;
private javax.swing.JTextField txt_diaChi;
private javax.swing.JTextField txt_hoLQ;
private javax.swing.JTextField txt_lichSuQT;
private javax.swing.JTextField txt_lq_den_ai;
private javax.swing.JTextField txt_maLQ;
private javax.swing.JTextField txt_namSinh;
private javax.swing.JComboBox<String> txt_noiDieuTri;
private javax.swing.JTextField txt_tenLQ;
private javax.swing.JComboBox<String> txt_trangThai;
// End of variables declaration//GEN-END:variables

}
