/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class QL_taikhoan_QL extends javax.swing.JFrame {

   DefaultTableModel tblModel = new DefaultTableModel();

public QL_taikhoan_QL() {
initComponents();
ngclList();
setLocationRelativeTo(null);

}
public void ngclList() {
       try{
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_quan_ly" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người quản lý","Họ","Tên","CMND/CCCD","Năm sinh", "Số điện thoại", "Địa chỉ"};
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_ql");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getInt("sdt");
                   row[6] = rs.getString("dia_chi");

                   this.tblModel.addRow(row);
                }                      
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }
}
/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

jLabel1 = new javax.swing.JLabel();
jLabel2 = new javax.swing.JLabel();
btn_add = new javax.swing.JButton();
jLabel3 = new javax.swing.JLabel();
btn_edit = new javax.swing.JButton();
jLabel4 = new javax.swing.JLabel();
btn_delete = new javax.swing.JButton();
jLabel5 = new javax.swing.JLabel();
jLabel6 = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
tbNCL = new javax.swing.JTable();
jLabel7 = new javax.swing.JLabel();
txt_maLQ = new javax.swing.JTextField();
txt_cmnd_cccd = new javax.swing.JTextField();
txt_hoLQ = new javax.swing.JTextField();
txt_tenLQ = new javax.swing.JTextField();
txt_namSinh = new javax.swing.JTextField();
txt_diaChi = new javax.swing.JTextField();
jLabel8 = new javax.swing.JLabel();
txt_SDT = new javax.swing.JTextField();
jButton1 = new javax.swing.JButton();
jButton2 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
jLabel1.setText("QUẢN LÝ TÀI KHOẢN QUẢN LÝ");

jLabel2.setText("Mã người quản lý");

btn_add.setText("THÊM MỚI");
btn_add.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btn_addActionPerformed(evt);
}
});

jLabel3.setText("Họ người quản lý");

btn_edit.setText("SỬA");
btn_edit.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btn_editActionPerformed(evt);
}
});

jLabel4.setText("Tên người quản lý");

btn_delete.setText("XÓA");
btn_delete.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btn_deleteActionPerformed(evt);
}
});

jLabel5.setText("CMND/CCCD");

jLabel6.setText("Năm sinh");

tbNCL.setModel(new javax.swing.table.DefaultTableModel(
new Object [][] {

},
new String [] {
"Mã người quản lý", "Họ", "Tên", "CMND/CCCD", "Năm sinh", "Số điện thoại", "Địa chỉ"
}
));
tbNCL.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
tbNCLMouseClicked(evt);
}
});
jScrollPane1.setViewportView(tbNCL);

jLabel7.setText("Địa chỉ");

txt_maLQ.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_maLQActionPerformed(evt);
}
});

txt_cmnd_cccd.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_cmnd_cccdActionPerformed(evt);
}
});

txt_hoLQ.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_hoLQActionPerformed(evt);
}
});

txt_tenLQ.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_tenLQActionPerformed(evt);
}
});

txt_namSinh.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_namSinhActionPerformed(evt);
}
});

txt_diaChi.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_diaChiActionPerformed(evt);
}
});

jLabel8.setText("Số điện thoại");

txt_SDT.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
txt_SDTActionPerformed(evt);
}
});

jButton1.setText("Quay lại");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});

jButton2.setText("Quản lý tài khoản, mật khẩu");
jButton2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton2ActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(49, 49, 49)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel2)
.addGap(30, 30, 30)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(txt_hoLQ, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
.addComponent(txt_maLQ)))
.addComponent(jLabel3)
.addComponent(jLabel6)
.addComponent(jLabel7)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel4)
.addComponent(jLabel5)
.addComponent(jLabel8))
.addGap(25, 25, 25)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
.addComponent(txt_cmnd_cccd, javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(txt_namSinh, javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(txt_diaChi, javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(txt_SDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
.addComponent(txt_tenLQ))))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(btn_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(231, 231, 231))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(22, 22, 22))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addGap(26, 26, 26)
.addComponent(jButton1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jLabel1)
.addGap(180, 180, 180)
.addComponent(jButton2)
.addGap(48, 48, 48))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(74, 74, 74)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(txt_maLQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel2)))
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1)
.addComponent(jButton1)
.addComponent(jButton2))
.addGap(36, 36, 36)
.addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3)
.addComponent(txt_hoLQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel4)
.addComponent(txt_tenLQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(19, 19, 19)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel5)
.addComponent(txt_cmnd_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createSequentialGroup()
.addGap(22, 22, 22)
.addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGap(16, 16, 16)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(txt_namSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel7)
.addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel8)
.addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createSequentialGroup()
.addGap(16, 16, 16)
.addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGap(75, 75, 75)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(30, Short.MAX_VALUE))
);

pack();
}// </editor-fold>//GEN-END:initComponents

private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
try{
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
String orc ="insert into Nguoi_quan_ly (ma_nguoi_ql, ho, ten, CMND, nam_sinh, sdt, dia_chi) values(?,?,?,?,?,?,?)";
PreparedStatement pst = con.prepareStatement(orc);
pst.setString(1, txt_maLQ.getText());
pst.setString(2, txt_hoLQ.getText());
pst.setString(3, txt_tenLQ.getText());
pst.setString(4, txt_cmnd_cccd.getText());
pst.setString(5, txt_namSinh.getText());
pst.setString(6, txt_SDT.getText());
pst.setString(7, txt_diaChi.getText());
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Insert Successfully");
} 
catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());
}
try{
DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();
tbModel.setRowCount(0);
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_quan_ly" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người quản lý","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Số điện thoại"};
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_ql");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getInt("sdt");
                   row[6] = rs.getString("dia_chi");

                   this.tblModel.addRow(row);
                }                      
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }
}//GEN-LAST:event_btn_addActionPerformed

private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
try{
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
String orc ="UPDATE Nguoi_quan_ly set ho=?, ten=?, CMND=?, nam_sinh=?, sdt=?, dia_chi=? where ma_nguoi_ql=?";
PreparedStatement pst = con.prepareStatement(orc);

pst.setString(1, txt_hoLQ.getText());
pst.setString(2, txt_tenLQ.getText());
pst.setString(3, txt_cmnd_cccd.getText());
pst.setString(4, txt_namSinh.getText());
pst.setString(5, txt_SDT.getText());
pst.setString(6, txt_diaChi.getText());
pst.setString(7, txt_maLQ.getText());
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Update Successfully");

} catch(Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());

}
try{
DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();
tbModel.setRowCount(0);
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_quan_ly" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người quản lý","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Số điện thoại"};
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_ql");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getInt("sdt");
                   row[6] = rs.getString("dia_chi");

                   this.tblModel.addRow(row);
                }                      
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }
}//GEN-LAST:event_btn_editActionPerformed

private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
try{
     Class.forName("oracle.jdbc.driver.OracleDriver");       
     Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
     String orc ="delete from Nguoi_quan_ly where ma_nguoi_ql=?";
      PreparedStatement pst = con.prepareStatement(orc);
      pst.setString(1, txt_maLQ.getText());
      pst.executeUpdate();
      JOptionPane.showMessageDialog(this,"Delete Successfully");
   } catch(Exception e)
{
       JOptionPane.showMessageDialog(this,e.getMessage());
} 

try{
DefaultTableModel tbModel = (DefaultTableModel) tbNCL.getModel();
tbModel.setRowCount(0);
            Class.forName("oracle.jdbc.driver.OracleDriver");       
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
            System.out.println("Connected to the database");           
            Statement st = con.createStatement();
            String orc = "select * from Nguoi_quan_ly" ;
            ResultSet rs = st.executeQuery(orc);
            this.tblModel = (DefaultTableModel)tbNCL.getModel(); 
            String column[] = {"Mã người quản lý","Họ","Tên","CMND/CCCD","Năm sinh", "Địa chỉ", "Số điện thoại"};
            this.tblModel.setColumnIdentifiers(column);
            this.tbNCL.setModel(tblModel);
            while(rs.next()){
                   Object[] row = new Object[10];
                   row[0] = rs.getString("ma_nguoi_ql");
                   row[1] = rs.getString("ho");
                   row[2] = rs.getString("ten");
                   row[3] = rs.getInt("CMND");
                   row[4] = rs.getInt("nam_sinh");
                   row[5] = rs.getInt("sdt");
                   row[6] = rs.getString("dia_chi");

                   this.tblModel.addRow(row);
                }                      
            }
       catch(Exception E){
            System.out.println("Connection failed");
            E.printStackTrace();
        }

}//GEN-LAST:event_btn_deleteActionPerformed

private void tbNCLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNCLMouseClicked

}//GEN-LAST:event_tbNCLMouseClicked

private void txt_maLQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maLQActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_maLQActionPerformed

private void txt_cmnd_cccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cmnd_cccdActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_cmnd_cccdActionPerformed

private void txt_hoLQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hoLQActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_hoLQActionPerformed

private void txt_tenLQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenLQActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_tenLQActionPerformed

private void txt_namSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namSinhActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_namSinhActionPerformed

private void txt_diaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diaChiActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_diaChiActionPerformed

private void txt_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_SDTActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Manage_admin ndt = new Manage_admin();
        ndt.show();}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
 */
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(QL_taikhoan_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(QL_taikhoan_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(QL_taikhoan_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(QL_taikhoan_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>

/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new QL_taikhoan_QL().setVisible(true);
}
});
}

// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton btn_add;
private javax.swing.JButton btn_delete;
private javax.swing.JButton btn_edit;
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JLabel jLabel7;
private javax.swing.JLabel jLabel8;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JTable tbNCL;
private javax.swing.JTextField txt_SDT;
private javax.swing.JTextField txt_cmnd_cccd;
private javax.swing.JTextField txt_diaChi;
private javax.swing.JTextField txt_hoLQ;
private javax.swing.JTextField txt_maLQ;
private javax.swing.JTextField txt_namSinh;
private javax.swing.JTextField txt_tenLQ;
// End of variables declaration//GEN-END:variables
}
