/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo_qly;
package Admin;
import Admin.Manage_admin;
import demo_qly.MANAGER.Manage;
import demo_qly.MANAGER.Manage;
import demo_qly.MANAGER.Manage_manager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import User.Manager_User;
/**
 *
 * @author PC
 */
public class Login extends javax.swing.JFrame {

Connection con;
PreparedStatement pst;
ResultSet rs;


public Login() {
initComponents();
        setLocationRelativeTo(null);

}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

jLabel1 = new javax.swing.JLabel();
jLabel2 = new javax.swing.JLabel();
edtUser = new javax.swing.JTextField();
btnLogin = new javax.swing.JButton();
btnReset = new javax.swing.JButton();
role = new javax.swing.JComboBox<>();
jLabel3 = new javax.swing.JLabel();
edtPassword = new javax.swing.JPasswordField();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

jLabel1.setText("Tên đăng nhập: ");

jLabel2.setText("Mật khẩu: ");

btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
btnLogin.setText("ĐĂNG NHẬP");
btnLogin.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnLoginActionPerformed(evt);
}
});

btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
btnReset.setText("ĐẶT LẠI");
btnReset.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
btnResetActionPerformed(evt);
}
});

role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager", "User" }));
role.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
roleActionPerformed(evt);
}
});

jLabel3.setText("Vai trò");

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(20, 20, 20)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel1)
.addComponent(jLabel2)
.addComponent(jLabel3))
.addGap(17, 17, 17)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(role, 0, 239, Short.MAX_VALUE)
.addComponent(edtUser)
.addComponent(edtPassword))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addGap(39, 39, 39)
.addComponent(btnLogin)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
.addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(40, 40, 40))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(46, 46, 46)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(edtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel1))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(edtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel2))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel3))
.addGap(31, 31, 31)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
.addContainerGap(23, Short.MAX_VALUE))
);

pack();
}// </editor-fold>//GEN-END:initComponents

private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try{
       Class.forName("oracle.jdbc.driver.OracleDriver");       
       Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "1");
       System.out.println("Connected to the database");  
          pst= con.prepareStatement("select TK.userName , TK.mat_khau, LTK.ten_loai_tk\n" +
                                    "from Tai_khoan TK \n" +
                                    "inner join Chi_tiet_tai_khoan CT on TK.userName = CT.userName\n" +
                                    "inner join Loai_tai_khoan LTK on LTK.ma_loai_tk = CT.ma_loai_tk\n" + 
                                    "where TK.userName=? and TK.mat_khau=? and LTK.ten_loai_tk=?");
          pst.setString(1, edtUser.getText());
          pst.setString(2, edtPassword.getText());
          pst.setString(3, String.valueOf(role.getSelectedItem()));
          ResultSet rs = pst.executeQuery();
          if (rs.next()){
          if (role.getSelectedIndex()==0)
          {
                  Manage_admin ad = new Manage_admin(); 
                  ad.setVisible(true);
                  this.setVisible(false);
                 
           }
           
           if (role.getSelectedIndex()==1)
          {
                  Manage_manager ma = new Manage_manager(); 
                  ma.setVisible(true);
                  this.setVisible(false);
           }
     
           if (role.getSelectedIndex()==2)
          {
                  Manager_User us = new Manager_User(); 
                  us.setVisible(true);
                  this.setVisible(false);
           }
}
else {
 JOptionPane.showMessageDialog(this,"Username or password wrong!!!");
              edtUser.setText("");
              edtPassword.setText("");
}
}
catch(Exception ex){

System.out.println(""+ex);
}

}//GEN-LAST:event_btnLoginActionPerformed

private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
// TODO add your handling code here:
    edtUser.setText("");
    edtPassword.setText("");

}//GEN-LAST:event_btnResetActionPerformed

private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed



}//GEN-LAST:event_roleActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {



java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new Login().setVisible(true);
}
});
}

// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton btnLogin;
private javax.swing.JButton btnReset;
private javax.swing.JPasswordField edtPassword;
private javax.swing.JTextField edtUser;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JComboBox<String> role;
// End of variables declaration//GEN-END:variables
}
